### PR TITLE
Hello world in C version

### PR DESCRIPTION
**Pull request by luanamarquesf**

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by rahulsain — CHANGES_REQUESTED** [review]
Please don't delete pre-existing files.

**Comment by luanamarquesf** [comment]
Hi, i did not delete. I found the following error while cloning

git clone https://github.com/luanamarquesf/hello-world
Cloning into 'hello-world'...
remote: Enumerating objects: 60, done.
remote: Counting objects: 100% (60/60), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 400 (delta 28), reused 8 (delta 2), pack-reused 340
Receiving objects: 100% (400/400), 88.93 KiB | 892.00 KiB/s, done.
Resolving deltas: 100% (182/182), done.
error: invalid path 'hello_world_program/LingoScriptingLanguage.'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

Em sáb, 17 de out de 2020 06:38, Rahul Sain <notifications@github.com>
escreveu:

**Comment by rahulsain** [comment]
@luanamarquesf That because you made changes in the new folder `hello_world_program/LingoScriptingLanguage` that doesn't exist in the repo.
Re forking the repo might delete that problem, you have to delete the repo locally on your computer

**Comment by luanamarquesf** [comment]
okk, thankss

Em sáb., 17 de out. de 2020 às 09:35, Rahul Sain <notifications@github.com>
escreveu:

**Pull request closed without merging**
